service: coffee-shop-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/CoffeeOrders

functions:
  createCoffee:
    handler: createCoffee.handler
    events:
      - http:
          path: coffee
          method: post
  
  getCoffee:
    handler: getCoffee.handler
    events:
      - http:
          path: coffee
          method: get
  
  updateCoffee:
    handler: updateCoffee.handler  
    events:
      - http:  
          path: coffee  
          method: put  
  
  deleteCoffee:  
    handler: deleteCoffee.handler
    events:
      - http:
          path: coffee
          method: delete
resources:
  Resources:
    CoffeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CoffeeOrders
        AttributeDefinitions:
          - AttributeName: OrderId
            AttributeType: S
          - AttributeName: CustomerName
            AttributeType: S
        KeySchema:
          - AttributeName: OrderId
            KeyType: HASH
          - AttributeName: CustomerName
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST